version: "3"
services:
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.arm-arch
    container_name: focalboard
    ports:
      - 9000:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    volumes:
      - "./data:/data"
